---
kind: Service
apiVersion: v1
metadata:
  name: pachd
  {{- if .Values.pachd.service.annotations }}
  annotations:
    {{ .Values.pachd.service.annotations | toYaml | indent 4 | trim  }}
  {{- end }}
  labels:
    app: pachd
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    suite: {{ template "fullname" . }}
spec:
  ports:
    - name: trace-port
      port: {{ .Values.pachd.service.port.trace }}
      targetPort: 651
      {{- if eq .Values.pachd.service.type "NodePort" }}
      nodePort: {{ .Values.pachd.service.nodePort.trace }}
      {{- end }}
    - name: api-http-port
      port: {{ .Values.pachd.service.port.http }}
      targetPort: 652
      {{- if eq .Values.pachd.service.type "NodePort" }}
      nodePort: {{ .Values.pachd.service.nodePort.http }}
      {{- end }}
    - name: api-grpc-port
      port: {{ .Values.pachd.service.port.grpc }}
      targetPort: 650
      {{- if eq .Values.pachd.service.type "NodePort" }}
      nodePort: {{ .Values.pachd.service.nodePort.grpc }}
      {{- end }}

  selector:
    app: pachd
  type: {{ .Values.pachd.service.type | quote }}
